/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ThinkPad
 */
public class menuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public menuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardPegawai = new javax.swing.JPanel();
        lb_pegawai = new javax.swing.JLabel();
        lb_iconPegawai = new javax.swing.JLabel();
        lb_jumlahPegawai = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cardPegawai.setBackground(new java.awt.Color(0, 255, 204));
        cardPegawai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_pegawai.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lb_pegawai.setText("PEGAWAI");

        lb_iconPegawai.setFont(new java.awt.Font("Roboto", 1, 60)); // NOI18N
        lb_iconPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_people_70px.png"))); // NOI18N

        lb_jumlahPegawai.setFont(new java.awt.Font("Roboto", 1, 60)); // NOI18N
        lb_jumlahPegawai.setText("60");

        javax.swing.GroupLayout cardPegawaiLayout = new javax.swing.GroupLayout(cardPegawai);
        cardPegawai.setLayout(cardPegawaiLayout);
        cardPegawaiLayout.setHorizontalGroup(
            cardPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPegawaiLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(lb_iconPegawai)
                .addGap(39, 39, 39))
            .addGroup(cardPegawaiLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lb_pegawai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cardPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cardPegawaiLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(lb_jumlahPegawai)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );
        cardPegawaiLayout.setVerticalGroup(
            cardPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPegawaiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_pegawai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_iconPegawai)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(cardPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPegawaiLayout.createSequentialGroup()
                    .addContainerGap(63, Short.MAX_VALUE)
                    .addComponent(lb_jumlahPegawai)
                    .addGap(30, 30, 30)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cardPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cardPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPegawai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_iconPegawai;
    private javax.swing.JLabel lb_jumlahPegawai;
    private javax.swing.JLabel lb_pegawai;
    // End of variables declaration//GEN-END:variables
}
